name: Build
on: [push, pull_request]
env:
  SSH_KEY: ${{ secrets.SSH_KEY }}
  DOWNLOAD_SERVER: ${{ secrets.DOWNLOAD_SERVER }}
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    name: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: lukka/get-cmake@latest

      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v2
        if: ${{ matrix.os != 'windows-latest' }} 
        with:
          version: latest
          platform: x64

      - name: Install Linux dependencies
        if: ${{ matrix.os == 'ubuntu-24.04' }} 
        run: sudo apt update && sudo apt install autoconf autoconf-archive automake libtool libltdl-dev build-essential

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 'ffc071e0c08432c60c9b64f00334c0227667931b'

      - name: Build project
        uses: lukka/run-cmake@v10
        with:
          configurePreset: ${{ matrix.os == 'windows-latest' && 'Windows' || 'Linux' }}
          buildPreset: 'default'

      - name: Install project
        run: cmake --install build --prefix install --config Debug

      - uses: actions/upload-artifact@v4
        with:
          name: pompom-${{ matrix.os }}
          path: install/